# Generated by Django 4.0.4 on 2022-04-26 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('registered_owner', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='building-cover')),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('building_status', models.CharField(choices=[('op', 'Vacancies Available'), ('um', 'Under Maintanance'), ('fo', 'Fully Occupied'), ('dc', 'Decomisioned')], max_length=5)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='This field is autogenerated', null=True, unique=True)),
                ('bathrooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('dimension', models.CharField(max_length=50)),
                ('kitchen', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('occupied', 'Currently Occupied'), ('ready', 'Ready To Move In'), ('hold', 'On Hold'), ('maintanance', 'Under Maintanance')], default='ready', max_length=20)),
                ('maintanance_status', models.CharField(choices=[('nm', 'Unchecked Report'), ('ip', 'Initiating Inspection'), ('ir', 'Maintainance In Progress'), ('op', 'No Active Reports'), ('rm', 'Remove')], default='op', max_length=6)),
                ('total_occupants', models.PositiveIntegerField(blank=True, help_text='Number of people in the unit', null=True)),
                ('water_available', models.BooleanField(default=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('electricity_available', models.BooleanField(default=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.building')),
            ],
            options={
                'verbose_name_plural': 'Rental Houses',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=55, unique=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Available Unit Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UnitAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to=property.models.get_house_album_path, width_field='image_width')),
                ('image_width', models.IntegerField(default=600)),
                ('image_height', models.IntegerField(default=500)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.rentalunit')),
            ],
        ),
        migrations.AddField(
            model_name='rentalunit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.unittype'),
        ),
        migrations.CreateModel(
            name='MaintananceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('maintanance_status', models.CharField(choices=[('Not Started', 'Not Yet Started'), ('In Progress', 'In progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('send_email', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.building')),
                ('notice_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.managers')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('registered_owner', models.CharField(max_length=50)),
                ('registered_country', models.CharField(default='Nassarawa', max_length=50)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='building',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.counties'),
        ),
        migrations.AddField(
            model_name='building',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.estate'),
        ),
        migrations.AddField(
            model_name='building',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_manager', to='registration.managers'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalunit',
            unique_together={('building', 'unit_number')},
        ),
    ]
